-- VARIABLE DECLARATION AND INITIALIZATION
DECLARE @SD DATE;
DECLARE @ED DATE;
DECLARE @S DATE;
DECLARE @E DATE;
SET @SD = GETDATE()-365*2;
SET @ED = GETDATE();
SET @S = '2013-12-30';
SET @E = '2013-12-31';

-- TABLE DECLARATION
DECLARE @T1 TABLE
(
	MED_REC_NO VARCHAR(20)
	, VISIT_ID VARCHAR(20)
	, ADMIT_DATE DATE
)
-- WHAT GOES INTO THE TABLE
INSERT INTO @T1
SELECT A.Med_Rec_No
, A.PtNo_Num
, A.Adm_Date
-- WHERE IT COMES FROM
FROM
(
	SELECT MED_REC_NO
	, PTNO_NUM
	, ADM_DATE

	FROM smsdss.BMH_PLM_PtAcct_V

	WHERE Plm_Pt_Acct_Type = 'I'
	AND PtNo_Num < '20000000'
	AND Dsch_Date BETWEEN @SD AND @ED
	AND drg_no IN (            -- DRG'S OF INTEREST
			'193','194','195'  -- PNEUMONIA
			,'291','292','293' -- CHF
			,'054','055','146' -- CANCER
			,'147','148','180'
			,'181','182','374'
			,'375','376','435'
			,'436','437','542'
			,'543','544','597'
			,'598','599','686'
			,'687','688','722'
			,'723','724','754'
			,'755','756','834'
			,'835','836','837'
			,'838','839','840'
			,'841','842','843'
			,'844','845','846'
			,'847','848','849'
		)
) A

/*
THIS QUERY WILL PULL IN DATA FROM THE SMSMIR.OBSV TABLE FOR THE DESIRED
RESPONSES
*/

;WITH WT AS (
	SELECT EPISODE_NO,
		MAX(CASE
				WHEN FORM_USAGE = 'Admission'
				AND OBSV_CD = 'A_WEIGHTOBTAINED'
				AND DSPLY_VAL = 'Actual'
				THEN 1
			END) AS [ACTUAL WEIGHT],
		MAX(CASE
				WHEN FORM_USAGE = 'ADMISSION'
				AND OBSV_CD = 'A_WEIGHTOBTAINED'
				AND DSPLY_VAL = 'STATED'
				THEN 1
			END) AS [STATED WEIGHT]
				
	FROM smsmir.obsv
	WHERE form_usage = 'ADMISSION'
	GROUP BY episode_no
)

/*
PULLING IT ALL TOGETHER
*/
SELECT T1.VISIT_ID
, ISNULL(WT.[ACTUAL WEIGHT], 0) AS [ACTUAL WEIGHT]
, ISNULL(WT.[STATED WEIGHT], 0) AS [STATED WEIGHT]
, CASE
	WHEN [ACTUAL WEIGHT] IS NULL AND [STATED WEIGHT] IS NULL
	THEN 1
	ELSE 0
  END AS [WAS WEIGHT INFO OBTAINED?]

FROM @T1 T1
LEFT JOIN WT WT
ON T1.VISIT_ID = WT.episode_no
WHERE T1.ADMIT_DATE BETWEEN @S AND @E

UNION ALL
SELECT 'TOTALS'
, SUM(
	CASE 
		WHEN WT.[ACTUAL WEIGHT] IS NULL
		THEN 0
		ELSE 1
	END)
, SUM(
	CASE
		WHEN WT.[STATED WEIGHT] IS NULL
		THEN 0
		ELSE 1
	END)
, SUM(
	CASE
		WHEN [ACTUAL WEIGHT] IS NULL AND [STATED WEIGHT] IS NULL
		THEN 1
		ELSE 0
	END)

FROM @T1 T1
LEFT JOIN WT WT
ON T1.VISIT_ID = WT.episode_no
WHERE T1.ADMIT_DATE BETWEEN @S AND @E