SELECT 
  CAST(DATEADD(DD, -1, DATEADD(WK, DATEDIFF(WK, 0, GETDATE()), -7)) AS DATE) AS [Sunday Last Week]
, DATENAME(dw, DATEADD(DD, -1, DATEADD(WK, DATEDIFF(WK, 0, GETDATE()), -7))) AS [Day]
, CAST(DATEADD(DD, -1, DATEADD(WK, DATEDIFF(WK, 0, GETDATE()), -1)) AS DATE) AS [Saturday Last Week]
, DATENAME(DW, DATEADD(DD, -1, DATEADD(WK, DATEDIFF(WK, 0, GETDATE()), -1))) AS [Day]
