-- VARIABLE DECLARTION AND VALUE INITIALIZATION
DECLARE @SD DATETIME
DECLARE @ED DATETIME
SET @SD = '2013-10-13'
SET @ED = '2013-10-19'

-- THIS CREATES A TABLE WHERE ALL THE DESIRED VISIT ID NUMBERS WILL GO
-- THIS TABLE IS A UNIQUE CLUSTER
CREATE TABLE #T1
(
VISIT_ID VARCHAR(20) UNIQUE CLUSTERED
)

-- WHAT GETS INSERTED INTO #T1. IT CAN BE QUICKER TO USE #T1 RATHER
-- THAN @T1
INSERT INTO #T1

SELECT DISTINCT PtNo_Num

FROM smsdss.BMH_PLM_PtAcct_V

WHERE Adm_Date BETWEEN @SD AND @ED
AND Plm_Pt_Acct_Type = 'I'
OPTION (RECOMPILE);

WITH OBS AS 
	(SELECT episode_no,
		MAX(CASE
				WHEN dsply_val LIKE 'Mitts%'
				THEN 1
			END) AS [MITTS]
		
		FROM smsmir.obsv
		
		-- FILTER(S) USED
		WHERE form_usage = 'Shift Flowsheet'
		--WHERE from_usage = 'Restraints FS'
		AND obsv_cd_ext_name = 'Safety'
		GROUP BY episode_no
	) 
SELECT #T1.VISIT_ID AS [VISIT ID]
, ISNULL(OBS.[MITTS], 0) AS [MITTS USED?]

-- DB(S) USED
FROM #T1
LEFT JOIN
OBS
ON #T1.VISIT_ID = OBS.episode_no

-- THIS MEANS EVERYONE WITH A 1 WILL SHOW UP FIRST
ORDER BY [MITTS USED?] DESC

-- THIS DROPS THE TEMPORARY TABLE FROM MEMORY
DROP TABLE #T1
