/*
THIS QUERY LOOKS FOR PATIENTS WITH A DISCHARGE DISPOTISION OF EXPIRED
AND THE PATIENT HAD SOME SORT OF OPERATING ROOM TIME CHARGED TO THEIR
VISIT ID
*/

SET ANSI_NULLS OFF
GO

-- VARIABLE INITIALIZATION AND DECLARATION
DECLARE @SD DATE;
DECLARE @ED DATE;
SET @SD = '2013-03-01';
SET @ED = '2013-12-31';

-- THE WITH STATEMENT HERE IS TREATING THE () LIKE A TABLE QUERY
WITH [SX FLAG] AS (
	-- COLUMN SELECTION
	SELECT DISTINCT
	PAV.PTNO_NUM AS [VISIT ID]
	, PAV.Med_Rec_No AS [MRN]
	, PAV.Pt_Name AS [NAME]
	, PAV.Dsch_Date AS [DISCHARGE DATE]
	, PAV.dsch_disp AS [DISPOSITION]
	-- THIS IS A FLAG SELECT THAT WILL GIVE A 1 WHEN A PT HAS OR TIME
	-- AND A 0 IF THEY DO NOT HAVE OR TIME DURING THEIR STAY
	, MAX(CASE
			WHEN ACDV.ACTV_GROUP = 'OR'
			THEN 1
			ELSE 0
		  END)
	  OVER (PARTITION BY PAV.PTNO_NUM) AS HASORTIME

	-- DB(S) USED
	FROM smsdss.BMH_PLM_PtAcct_V PAV
	JOIN smsdss.actv_fct_v AFV     -- <-- THIS WILL HELP IDENTIFY OR TIME
	ON PAV.Pt_No = AFV.pt_id       -- <-- DITTO
	JOIN smsdss.actv_cd_dim_v ACDV -- <-- DITTO
	ON AFV.actv_cd = ACDV.actv_cd  -- <-- DITTO

	-- FILTER(S)
	-- ALL OF THE FOLLOWING ARE CODES THAT IDENTIFY SOME TYPE OF
	-- MORTALITY
	WHERE dsch_disp IN (
		'C1A','C1N','C1Z','C2A','C2N','C2Z','C3A','C3N','C3Z','C4A'
		,'C4N','C4Z','C7A','C7N','C7Z','C8A','C8N','C8Z','D1A','D1N'
		,'D1Z','D2A','D2N','D2Z','D3A','D3N','D3Z','D4A','D4N','D4Z'
		,'D7A','D7N','D7Z','D8A','D8N','D8Z'
	)
	AND Dsch_Date >= @SD 
	AND Dsch_Date < @ED
	AND Plm_Pt_Acct_Type = 'I'
	AND PtNo_Num < '20000000'
)
-- COLUMN SELECTION FROM WITH() QUERY
SELECT [SX FLAG].[VISIT ID]
, [SX FLAG].MRN
, [SX FLAG].NAME
, [SX FLAG].[DISCHARGE DATE]
, [SX FLAG].DISPOSITION

-- WHERE THE DATA COMES FROM
FROM [SX FLAG]

-- FILTER(S)
WHERE [SX FLAG].HASORTIME = 1
