SELECT [TRANS_DATE]
, [TRANS_MONTH] = DATEPART(MONTH, [TRANS_DATE])
, [TRNS_QTR] = DATEPART(QUARTER, [TRANS_DATE])
, [TRNS_DOW] = DATEPART(WEEKDAY, [TRANS_DATE])
, [TRNS_DOW_LBL] = CASE
	WHEN DATEPART(WEEKDAY, [TRANS_DATE]) = 1 THEN 'SUNDAY'
	WHEN DATEPART(WEEKDAY, [TRANS_DATE]) = 2 THEN 'MONDAY'
	WHEN DATEPART(WEEKDAY, [TRANS_DATE]) = 3 THEN 'TUESDAY'
	WHEN DATEPART(WEEKDAY, [TRANS_DATE]) = 4 THEN 'WEDNESDAY'
	WHEN DATEPART(WEEKDAY, [TRANS_DATE]) = 5 THEN 'THURSDAY'
	WHEN DATEPART(WEEKDAY, [TRANS_DATE]) = 6 THEN 'FRIDAY'
	WHEN DATEPART(WEEKDAY, [TRANS_DATE]) = 7 THEN 'SATURDAY'
  END 
, [PAT_NUM]
, [UNIT_COST]
, [PRIMARY_NAME]
, [TRANS_QTY]
, [DISPENSING_UNIT]
, [ORD_DRNAME]
, [ORD_DRNO]
, PDM.med_staff_dept
, PDM.src_spclty_cd
, [PRICE]
, [CDM_NO]
, [ORDER_COST] = CAST(([UNIT_COST] * [TRANS_QTY]) AS money)
, [ORDER_MARK_UP] = CASE
	WHEN ([UNIT_COST] * [TRANS_QTY]) = 0
		THEN 0
	ELSE ROUND(([PRICE] / ([UNIT_COST] * [TRANS_QTY])), 2)
  END

FROM [smsdss].[c_PharmacyJanJun2017] AS A
LEFT OUTER JOIN smsdss.pract_dim_v AS PDM
ON A.ORD_DRNO = PDM.src_pract_no
	AND PDM.orgz_cd = 'S0X0'