-- VARIABLE DECLARATION
DECLARE @DAY INT, @MONTH INT, @YEAR INT;

-- VARIABLE INITIALIZATION
SET @DAY = 2;
SET @MONTH = 6;
SET @YEAR = 2013;

-- COLUMN SELECTION
SELECT
	(SELECT COUNT(NURS_STA)
	 FROM smsdss.dly_cen_occ_fct
	 WHERE DATEPART(DAY,CEN_DATE)=@DAY
	 AND DATEPART(MONTH,CEN_DATE)=@MONTH
	 AND DATEPART(YEAR,cen_date)=@YEAR
	 AND nurs_sta = '1EAS') AS '1EAS',
	(SELECT COUNT(NURS_STA)
	 FROM smsdss.dly_cen_occ_fct
	 WHERE DATEPART(DAY,CEN_DATE)=@DAY
	 AND DATEPART(MONTH,CEN_DATE)=@MONTH
	 AND DATEPART(YEAR,cen_date)=@YEAR
	 AND nurs_sta = '2CAD') AS '2CAD',
	(SELECT COUNT(NURS_STA)
	 FROM smsdss.dly_cen_occ_fct
	 WHERE DATEPART(DAY,CEN_DATE)=@DAY
	 AND DATEPART(MONTH,CEN_DATE)=@MONTH
	 AND DATEPART(YEAR,cen_date)=@YEAR
	 AND nurs_sta = '2MAI') AS '2MAI',
	(SELECT COUNT(NURS_STA)
	 FROM smsdss.dly_cen_occ_fct
	 WHERE DATEPART(DAY,CEN_DATE)=@DAY
	 AND DATEPART(MONTH,CEN_DATE)=@MONTH
	 AND DATEPART(YEAR,cen_date)=@YEAR
	 AND nurs_sta = '2NOR') AS '2NOR',
	(SELECT COUNT(NURS_STA)
	 FROM smsdss.dly_cen_occ_fct
	 WHERE DATEPART(DAY,CEN_DATE)=@DAY
	 AND DATEPART(MONTH,CEN_DATE)=@MONTH
	 AND DATEPART(YEAR,cen_date)=@YEAR
	 AND nurs_sta = '2PED') AS '2PED',
	(SELECT COUNT(NURS_STA)
	 FROM smsdss.dly_cen_occ_fct
	 WHERE DATEPART(DAY,CEN_DATE)=@DAY
	 AND DATEPART(MONTH,CEN_DATE)=@MONTH
	 AND DATEPART(YEAR,cen_date)=@YEAR
	 AND nurs_sta = '2SOU') AS '2SOU',
	(SELECT COUNT(NURS_STA)
	 FROM smsdss.dly_cen_occ_fct
	 WHERE DATEPART(DAY,CEN_DATE)=@DAY
	 AND DATEPART(MONTH,CEN_DATE)=@MONTH
	 AND DATEPART(YEAR,cen_date)=@YEAR
	 AND nurs_sta = '3NOR') AS '3NOR',
	(SELECT COUNT(NURS_STA)
	 FROM smsdss.dly_cen_occ_fct
	 WHERE DATEPART(DAY,CEN_DATE)=@DAY
	 AND DATEPART(MONTH,CEN_DATE)=@MONTH
	 AND DATEPART(YEAR,cen_date)=@YEAR
	 AND nurs_sta = '3SOU') AS '3SOU',
	(SELECT COUNT(NURS_STA)
	 FROM smsdss.dly_cen_occ_fct
	 WHERE DATEPART(DAY,CEN_DATE)=@DAY
	 AND DATEPART(MONTH,CEN_DATE)=@MONTH
	 AND DATEPART(YEAR,cen_date)=@YEAR
	 AND nurs_sta = '4NOR') AS '4NOR',
	(SELECT COUNT(NURS_STA)
	 FROM smsdss.dly_cen_occ_fct
	 WHERE DATEPART(DAY,CEN_DATE)=@DAY
	 AND DATEPART(MONTH,CEN_DATE)=@MONTH
	 AND DATEPART(YEAR,cen_date)=@YEAR
	 AND nurs_sta = '4SOU') AS '4SOU',
	(SELECT COUNT(NURS_STA)
	 FROM smsdss.dly_cen_occ_fct
	 WHERE DATEPART(DAY,CEN_DATE)=@DAY
	 AND DATEPART(MONTH,CEN_DATE)=@MONTH
	 AND DATEPART(YEAR,cen_date)=@YEAR
	 AND nurs_sta = 'CCU') AS 'CCU',
	(SELECT COUNT(NURS_STA)
	 FROM smsdss.dly_cen_occ_fct
	 WHERE DATEPART(DAY,CEN_DATE)=@DAY
	 AND DATEPART(MONTH,CEN_DATE)=@MONTH
	 AND DATEPART(YEAR,cen_date)=@YEAR
	 AND nurs_sta = 'EMER') AS 'EMER',
	(SELECT COUNT(NURS_STA)
	 FROM smsdss.dly_cen_occ_fct
	 WHERE DATEPART(DAY,CEN_DATE)=@DAY
	 AND DATEPART(MONTH,CEN_DATE)=@MONTH
	 AND DATEPART(YEAR,cen_date)=@YEAR
	 AND nurs_sta = 'MICU') AS 'MICU',
	(SELECT COUNT(NURS_STA)
	 FROM smsdss.dly_cen_occ_fct
	 WHERE DATEPART(DAY,CEN_DATE)=@DAY
	 AND DATEPART(MONTH,CEN_DATE)=@MONTH
	 AND DATEPART(YEAR,cen_date)=@YEAR
	 AND nurs_sta = 'PSY') AS 'PSY',
	(SELECT COUNT(NURS_STA)
	 FROM smsdss.dly_cen_occ_fct
	 WHERE DATEPART(DAY,CEN_DATE)=@DAY
	 AND DATEPART(MONTH,CEN_DATE)=@MONTH
	 AND DATEPART(YEAR,cen_date)=@YEAR
	 AND nurs_sta = 'SICU') AS 'SICU',
	(SELECT COUNT(NURS_STA)
	 FROM smsdss.dly_cen_occ_fct
	 WHERE DATEPART(DAY,CEN_DATE)=@DAY
	 AND DATEPART(MONTH,CEN_DATE)=@MONTH
	AND DATEPART(YEAR,cen_date)=@YEAR) AS 'GRAND TOTAL'