USE [SMSPHDSSS0X0]
GO
/****** Object:  StoredProcedure [smsdss].[c_HOSIM_IP_Rad_Order_Utilization_Rpt_Tbl_sp]    Script Date: 10/20/2017 9:11:46 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [smsdss].[c_HOSIM_IP_Rad_Order_Utilization_Rpt_Tbl_sp]

AS

SET NOCOUNT ON;
SET ANSI_WARNINGS OFF;

/*
Author: Steven P Sanderson II, MPH
Department: Finance, Revenue Cycle

This stored procedure will take data generated by the stored procedure smsdss.c_Lab_Rad_Order_Utilization_sp
that inserts records into smsdss.c_LabRad_OrdUtil_by_DschDT

Predicate: smsdss.c_Lab_Rad_Order_Utilization_sp
Procedure must run after smsdss.c_Lab_Rad_Order_Utilization_sp has completed

The report table starts with patients who are discharged in 2017.

The table will only contain orders for:
	1. Hospitalists
	2. Discharge DateTime is greater than or equal to 2017-01-01
	3. Inpatients Only
	4. Total charges are > 0
	5. Service department description is Radiology
	6. The service sub-department description is in ('MRI', 'Cat Scan')

v1 - 2017-10-11 - Initial stored procedure creation
V2 - 2017-10-20 - Fix to collect only orders from Hospitalists, the attending can be any
                  specialty
*/

IF NOT EXISTS (
	SELECT TOP 1 * FROM sysobjects WHERE name = 'c_HOSIM_IP_RadOrdersUtil_RptTbl' AND xtype = 'U'
)

BEGIN

	-- DATE VARIABLE DEC AND SET
	DECLARE @START DATETIME;
	DECLARE @END   DATETIME;

	SET @START = '2017-01-01';
	SET @END   = DATEADD(MM, DATEDIFF(MM, 0, GETDATE()), 0); -- FIRST DAY OF CURRENT MONTH

	-- CREATE TABLE IF NOT EXISTS
	CREATE TABLE smsdss.c_HOSIM_IP_RadOrdersUtil_RptTbl (
		PK INT IDENTITY(1, 1) NOT NULL PRIMARY KEY
		, MRN INT NULL
		, Encounter INT NULL
		, Dsch_DateTime DATETIME NULL
		, LOS INT NULL
		, Dsch_Year VARCHAR(10) NULL
		, Dsch_Qtr VARCHAR(10) NULL
		, Dsch_Mo VARCHAR(10) NULL
		, Dsch_Hr VARCHAR(10) NULL
		, ED_IP_FLAG VARCHAR(2) NULL
		, Atn_Dr_No VARCHAR(6) NULL
		, Atn_Dr VARCHAR(75) NULL
		, Atn_Dr_Spclty_Cd VARCHAR(10) NULL
		, LIHN_Svc_Line VARCHAR(100) NULL
		, ROM INT NULL
		, SOI INT NULL
		, APR_DRG VARCHAR(4) NULL
		, Ord_Pty_Number VARCHAR(10) NULL
		, Ordering_Party VARCHAR(100) NULL
		, Ord_Pty_Spclty VARCHAR(10) NULL
		, Ord_Set_ID VARCHAR(20) NULL
		, Order_No VARCHAR(20) NULL
		, Ord_Occ_No VARCHAR(20) NULL
		, Ord_Occ_Obj_ID VARCHAR(20) NULL
		, Order_Loc VARCHAR(20) NULL
		, Svc_Cd VARCHAR(20) NULL
		, Svc_Desc VARCHAR(200) NULL
		, Performing_Dept VARCHAR(20) NULL
		, Svc_Dept_Desc VARCHAR(20) NULL
		, Svc_Sub_Dept VARCHAR(20) NULL
		, Svc_Sub_Dept_Desc VARCHAR(30) NULL
		, Ord_Entry_DTime DATETIME NULL
		, Ord_Ent_Yr VARCHAR(10) NULL
		, Ord_Ent_Qtr VARCHAR(10) NULL
		, Ord_Ent_Mo VARCHAR(10) NULL
		, Ord_Ent_Hr VARCHAR(10) NULL
		, Ord_Start_DTime DATETIME NULL
		, Ord_Start_Yr VARCHAR(10) NULL
		, Ord_Start_Qtr VARCHAR(10) NULL
		, Ord_Start_Mo VARCHAR(10) NULL
		, Ord_Start_Hr VARCHAR(10) NULL
		, Ord_Stop_DTime DATETIME NULL
		, Ord_Stop_Yr VARCHAR(10) NULL
		, Ord_Stop_Qtr VARCHAR(10) NULL
		, Ord_Stop_Mo VARCHAR(10) NULL
		, Ord_Stop_Hr VARCHAR(10) NULL
		, Order_Status VARCHAR(20) NULL
		, Order_Occ_Status VARCHAR(20) NULL
		, Dup_Order VARCHAR(10) NULL
		, LabRad_RunDate DATE NULL
		, LabRad_RunDT DATETIME NULL
		, RadRptTbl_RunDate DATE NULL
		, RadRptTbl_RunDT DATETIME NULL
		, Performance FLOAT NULL
	);

	SELECT a.MRN
	, a.Encounter
	, a.Dsch_DateTime
	, CAST(plm.Days_Stay AS int) AS [LOS]
	, a.Dsch_Year
	, a.Dsch_Qtr
	, a.Dsch_Mo
	, a.Dsch_Hr
	, a.ED_IP_FLAG
	, plm.Atn_Dr_No
	, pdv.pract_rpt_name
	, pdv.src_spclty_cd
	, CASE
		WHEN plm.prin_dx_cd_schm = '9'
			THEN lihn_icd9.LIHN_Service_Line
		WHEN plm.prin_dx_cd_schm = '0'
			THEN lihn_icd10.LIHN_Service_Line
		ELSE ''
	  END AS [LIHN_Svc_Line]
	, c.RISK_OF_MORTALITY
	, c.SEVERITY_OF_ILLNESS
	, c.APRDRGNO
	, a.Ord_Pty_Number
	, a.Ordering_Party
	, a.Ord_Pty_Spclty
	, a.Ord_Set_ID
	, a.Order_No
	, a.Ord_Occ_No
	, a.Ord_Occ_Obj_ID
	, a.Order_Loc
	, a.Svc_Cd
	, a.Svc_Desc
	, a.Performing_Dept
	, a.Svc_Dept_Desc
	, a.Svc_Sub_Dept
	, a.Svc_Sub_Dept_Desc
	, a.Ord_Entry_DTime
	, a.Ord_Ent_Yr
	, a.Ord_Ent_Qtr
	, a.Ord_Ent_Mo
	, a.Ord_Ent_Hr
	, a.Ord_Start_DTime
	, a.Ord_Start_Yr
	, a.Ord_Start_Qtr
	, a.Ord_Start_Mo
	, a.Ord_Start_Hr
	, a.Ord_Stop_DTime
	, a.Ord_Stop_Yr
	, a.Ord_Stop_Qtr
	, a.Ord_Stop_Mo
	, a.Ord_Stop_Hr
	, a.Order_Status
	, a.Order_Occ_Status
	, a.Dup_Order
	, a.RunDate AS [LabRad_RunDate]
	, a.RunDateTime AS [LabRad_RunDT]
	, CAST(GETDATE() AS date) AS [RadRptTbl_RunDate]
	, GETDATE() AS [RadRptTbl_RunDT]

	INTO #tempa

	FROM smsdss.c_LabRad_OrdUtil_by_DschDT               AS a
	LEFT OUTER JOIN smsdss.BMH_PLM_PtAcct_V              AS plm
	ON a.encounter = plm.PtNo_Num
	LEFT OUTER JOIN smsdss.pract_dim_v                   AS pdv
	ON plm.atn_dr_no = pdv.src_pract_no
		and plm.regn_hosp = pdv.orgz_cd
	LEFT OUTER JOIN smsdss.c_LIHN_Svc_Lines_Rpt2_v       AS lihn_icd9
	ON plm.Pt_No = lihn_icd9.pt_id
		and plm.prin_dx_cd_schm = lihn_icd9.icd_cd_schm
	LEFT OUTER JOIN smsdss.c_LIHN_Svc_Lines_Rpt2_ICD10_v AS lihn_icd10
	ON plm.Pt_No = lihn_icd10.pt_id
		and plm.prin_dx_cd_schm = lihn_icd10.icd_cd_schm
	LEFT OUTER JOIN Customer.Custom_DRG                  AS c
	ON a.Encounter = c.PATIENT#

	WHERE a.Ord_Pty_Spclty = 'HOSIM'
	AND Dsch_DateTime >= @START
	AND Dsch_DateTime < @END
	AND ED_IP_FLAG = 'IP'
	AND plm.tot_chg_amt > 0
	AND Svc_Dept_Desc = 'Radiology'
	AND Svc_Sub_Dept_Desc IN (
		'MRI'
		, 'Cat Scan'
	)

	ORDER BY a.Dsch_DateTime
	;

	-----

	INSERT INTO smsdss.c_HOSIM_IP_RadOrdersUtil_RptTbl

	SELECT A.*
	, B.Performance

	FROM #tempa AS A
	LEFT JOIN smsdss.c_LIHN_SPARCS_BenchmarkRates AS B
	ON A.SEVERITY_OF_ILLNESS = B.SOI
		AND A.APRDRGNO = B.[APRDRG Code]
		AND B.[Measure ID] = 4
		AND B.[Benchmark ID] = 3
		AND A.LIHN_Svc_Line = B.[LIHN Service Line]
	WHERE B.Performance IS NOT NULL
	;

	DROP TABLE #tempa;

END

ELSE BEGIN
	-- If the table already exists then insert records into it and make sure it was not already
	-- run for the day

	-- DATE VARIABLE DEC AND SET
	DECLARE @START_B DATETIME;
	DECLARE @END_B   DATETIME;

	SET @START_B = DATEADD(mm, datediff(mm, 0, getdate()) -1, 0); -- FIRST DAY OF PREVIOUS MONTH
	SET @END_B   = DATEADD(MM, DATEDIFF(MM, 0, GETDATE()), 0); -- FIRST DAY OF CURRENT MONTH

	SELECT a.MRN
	, a.Encounter
	, a.Dsch_DateTime
	, CAST(plm.Days_Stay AS int) AS [LOS]
	, a.Dsch_Year
	, a.Dsch_Qtr
	, a.Dsch_Mo
	, a.Dsch_Hr
	, a.ED_IP_FLAG
	, plm.Atn_Dr_No
	, pdv.pract_rpt_name
	, pdv.src_spclty_cd
	, CASE
		WHEN plm.prin_dx_cd_schm = '9'
			THEN lihn_icd9.LIHN_Service_Line
		WHEN plm.prin_dx_cd_schm = '0'
			THEN lihn_icd10.LIHN_Service_Line
		ELSE ''
	  END AS [LIHN_Svc_Line]
	, c.RISK_OF_MORTALITY
	, c.SEVERITY_OF_ILLNESS
	, c.APRDRGNO
	, a.Ord_Pty_Number
	, a.Ordering_Party
	, a.Ord_Pty_Spclty
	, a.Ord_Set_ID
	, a.Order_No
	, a.Ord_Occ_No
	, a.Ord_Occ_Obj_ID
	, a.Order_Loc
	, a.Svc_Cd
	, a.Svc_Desc
	, a.Performing_Dept
	, a.Svc_Dept_Desc
	, a.Svc_Sub_Dept
	, a.Svc_Sub_Dept_Desc
	, a.Ord_Entry_DTime
	, a.Ord_Ent_Yr
	, a.Ord_Ent_Qtr
	, a.Ord_Ent_Mo
	, a.Ord_Ent_Hr
	, a.Ord_Start_DTime
	, a.Ord_Start_Yr
	, a.Ord_Start_Qtr
	, a.Ord_Start_Mo
	, a.Ord_Start_Hr
	, a.Ord_Stop_DTime
	, a.Ord_Stop_Yr
	, a.Ord_Stop_Qtr
	, a.Ord_Stop_Mo
	, a.Ord_Stop_Hr
	, a.Order_Status
	, a.Order_Occ_Status
	, a.Dup_Order
	, a.RunDate AS [LabRad_RunDate]
	, a.RunDateTime AS [LabRad_RunDT]
	, CAST(GETDATE() AS date) AS [RadRptTbl_RunDate]
	, GETDATE() AS [RadRptTbl_RunDT]

	INTO #tempb

	FROM smsdss.c_LabRad_OrdUtil_by_DschDT               AS a
	LEFT OUTER JOIN smsdss.BMH_PLM_PtAcct_V              AS plm
	ON a.encounter = plm.PtNo_Num
	LEFT OUTER JOIN smsdss.pract_dim_v                   AS pdv
	ON plm.atn_dr_no = pdv.src_pract_no
		and plm.regn_hosp = pdv.orgz_cd
	LEFT OUTER JOIN smsdss.c_LIHN_Svc_Lines_Rpt2_v       AS lihn_icd9
	ON plm.Pt_No = lihn_icd9.pt_id
		and plm.prin_dx_cd_schm = lihn_icd9.icd_cd_schm
	LEFT OUTER JOIN smsdss.c_LIHN_Svc_Lines_Rpt2_ICD10_v AS lihn_icd10
	ON plm.Pt_No = lihn_icd10.pt_id
		and plm.prin_dx_cd_schm = lihn_icd10.icd_cd_schm
	LEFT OUTER JOIN Customer.Custom_DRG                  AS c
	ON a.Encounter = c.PATIENT#

	WHERE a.Ord_Pty_Spclty = 'HOSIM'
	AND Dsch_DateTime >= @START_B
	AND Dsch_DateTime < @END_B
	AND ED_IP_FLAG = 'IP'
	AND plm.tot_chg_amt > 0
	AND Svc_Dept_Desc = 'Radiology'
	AND Svc_Sub_Dept_Desc IN (
		'MRI'
		, 'Cat Scan'
	)

	ORDER BY a.Dsch_DateTime
	;

	-----

	INSERT INTO smsdss.c_HOSIM_IP_RadOrdersUtil_RptTbl

	SELECT A.*
	, B.Performance

	FROM #tempb AS A
	LEFT JOIN smsdss.c_LIHN_SPARCS_BenchmarkRates AS B
	ON A.SEVERITY_OF_ILLNESS = B.SOI
		AND A.APRDRGNO = B.[APRDRG Code]
		AND B.[Measure ID] = 4
		AND B.[Benchmark ID] = 3
		AND A.LIHN_Svc_Line = B.[LIHN Service Line]
	WHERE B.Performance IS NOT NULL
	-- Make sure the SP was not run today
	AND CAST(GETDATE() AS DATE) <> ISNULL((SELECT MAX(RadRptTbl_RunDate) FROM smsdss.c_HOSIM_IP_RadOrdersUtil_RptTbl), GETDATE() - 1)
	-- Make sure no order occurences that are already in the table get re-inserted
	AND A.Ord_Occ_No NOT IN (
		SELECT DISTINCT(Ord_Occ_No)
		FROM smsdss.c_HOSIM_IP_RadOrdersUtil_RptTbl
	)
	;

	DROP TABLE #tempb;

END
;