DECLARE @TODAY DATE;
DECLARE @START DATE;
DECLARE @END   DATE;

SET @TODAY = GETDATE();
SET @START = DATEADD(YEAR, DATEDIFF(YEAR, 0, @TODAY) - 1, 0);
SET @END   = DATEADD(YEAR, DATEDIFF(YEAR, 0, @TODAY),0);

SELECT @TODAY AS [TODAY]
, @START AS [START]
, @END AS [END]