SELECT PAV.Med_Rec_No,
	PAV.PtNo_Num,
	PAV.unit_seq_no,
	PAV.Plm_Pt_Acct_Type,
	PAV.pt_type,
	PTT.pt_type_cd_desc,
	PAV.fc,
	FDV.fc_name,
	CAST(PAV.ADM_DATE AS DATE) AS [Adm_Date],
	CAST(PAV.Dsch_Date AS DATE) AS [Dsch_Date],
	PAV.Pyr1_Co_Plan_Cd AS [Ins1],
	PDV.pyr_name,
	PDV.pyr_group2,
	PAV.hosp_svc,
	HOS.hosp_svc_name,
	PAV.tot_chg_amt,
	PAV.tot_adj_amt,
	PAV.tot_pay_amt,
	PAV.Tot_Amt_Due,
	pav.drg_no,
	DDV.drg_name,
	CASE 
		WHEN PAV.Plm_Pt_Acct_Type = 'I'
			THEN PAV.Prin_Icd10_Proc_Cd
		WHEN PAV.Plm_Pt_Acct_Type != 'I'
			THEN PAV.Prin_Hcpc_Proc_Cd
		END AS [Principal_Procedure_Code],
	COALESCE(SPDVA.alt_clasf_desc, SPDVB.alt_clasf_desc) AS [Prin_Proc_Name],
	[PIF_Flag] = CASE 
		WHEN PAV.plm_pt_acct_type = 'I'
			AND PAV.TOT_AMT_DUE <= 500
			THEN 1
		WHEN PAV.PLM_PT_ACCT_TYPE = 'O'
			AND PAV.HOSP_SVC = 'CTH'
			AND PAV.TOT_AMT_DUE <= 250
			THEN 1
		WHEN PAV.PLM_PT_ACCT_TYPE = 'O'
			AND PAV.HOSP_SVC = 'D23'
			AND PAV.TOT_AMT_DUE <= 250
			THEN 1
		WHEN PAV.PLM_PT_ACCT_TYPE = 'O'
			AND PAV.HOSP_SVC = 'DIA'
			AND PAV.TOT_AMT_DUE <= 250
			THEN 1
		WHEN PAV.PLM_PT_ACCT_TYPE = 'O'
			AND PAV.HOSP_SVC = 'DMS'
			AND PAV.TOT_AMT_DUE <= 250
			THEN 1
		WHEN PAV.PLM_PT_ACCT_TYPE = 'O'
			AND PAV.HOSP_SVC = 'OBV'
			AND PAV.TOT_AMT_DUE <= 250
			THEN 1
		WHEN PAV.PLM_PT_ACCT_TYPE = 'O'
			AND PAV.HOSP_SVC = 'AMB'
			AND PAV.TOT_AMT_DUE <= 150
			THEN 1
		WHEN PAV.PLM_PT_ACCT_TYPE = 'O'
			AND PAV.HOSP_SVC = 'EME'
			AND PAV.TOT_AMT_DUE <= 150
			THEN 1
		WHEN PAV.PLM_PT_ACCT_TYPE = 'O'
			AND PAV.HOSP_SVC = 'EOR'
			AND PAV.TOT_AMT_DUE <= 150
			THEN 1
		WHEN PAV.PLM_PT_ACCT_TYPE = 'O'
			AND PAV.HOSP_SVC = 'EPC'
			AND PAV.TOT_AMT_DUE <= 150
			THEN 1
		WHEN PAV.PLM_PT_ACCT_TYPE = 'O'
			AND PAV.HOSP_SVC = 'INF'
			AND PAV.TOT_AMT_DUE <= 150
			THEN 1
		WHEN PAV.PLM_PT_ACCT_TYPE = 'O'
			AND PAV.HOSP_SVC = 'BFM'
			AND PAV.TOT_AMT_DUE <= 50
			THEN 1
		WHEN PAV.PLM_PT_ACCT_TYPE = 'O'
			AND PAV.HOSP_SVC = 'OPD'
			AND PAV.TOT_AMT_DUE <= 50
			THEN 1
		WHEN PAV.PLM_PT_ACCT_TYPE = 'O'
			AND PAV.HOSP_SVC = 'PRO'
			AND PAV.TOT_AMT_DUE <= 50
			THEN 1
		WHEN PAV.PLM_PT_ACCT_TYPE = 'O'
			AND PAV.HOSP_SVC = 'SPE'
			AND PAV.TOT_AMT_DUE <= 50
			THEN 1
		WHEN PAV.PLM_PT_ACCT_TYPE = 'O'
			AND PAV.HOSP_SVC = 'WCC'
			AND PAV.TOT_AMT_DUE <= 50
			THEN 1
		WHEN PAV.PLM_PT_ACCT_TYPE = 'O'
			AND PAV.HOSP_SVC = 'WCH'
			AND PAV.TOT_AMT_DUE <= 50
			THEN 1
		WHEN PAV.PLM_PT_ACCT_TYPE = 'O'
			AND PAV.HOSP_SVC = 'BHC'
			AND PAV.TOT_AMT_DUE <= 25
			THEN 1
		WHEN PAV.PLM_PT_ACCT_TYPE = 'O'
			AND PAV.HOSP_SVC = 'BPC'
			AND PAV.TOT_AMT_DUE <= 25
			THEN 1
		WHEN PAV.PLM_PT_ACCT_TYPE = 'O'
			AND PAV.HOSP_SVC = 'MBV'
			AND PAV.TOT_AMT_DUE <= 25
			THEN 1
		WHEN PAV.PLM_PT_ACCT_TYPE = 'O'
			AND PAV.HOSP_SVC = 'MHO'
			AND PAV.TOT_AMT_DUE <= 25
			THEN 1
		WHEN PAV.PLM_PT_ACCT_TYPE = 'O'
			AND PAV.HOSP_SVC = 'MNV'
			AND PAV.TOT_AMT_DUE <= 25
			THEN 1
		WHEN PAV.PLM_PT_ACCT_TYPE = 'O'
			AND PAV.HOSP_SVC = 'MOA'
			AND PAV.TOT_AMT_DUE <= 25
			THEN 1
		WHEN PAV.PLM_PT_ACCT_TYPE = 'O'
			AND PAV.HOSP_SVC = 'MSR'
			AND PAV.TOT_AMT_DUE <= 25
			THEN 1
		WHEN PAV.PLM_PT_ACCT_TYPE = 'O'
			AND PAV.HOSP_SVC = 'PET'
			AND PAV.TOT_AMT_DUE <= 25
			THEN 1
		WHEN PAV.PLM_PT_ACCT_TYPE = 'O'
			AND PAV.HOSP_SVC = 'REH'
			AND PAV.TOT_AMT_DUE <= 25
			THEN 1
		WHEN PAV.PLM_PT_ACCT_TYPE = 'O'
			AND PAV.HOSP_SVC = 'SCR'
			AND PAV.TOT_AMT_DUE <= 25
			THEN 1
		WHEN PAV.PLM_PT_ACCT_TYPE = 'O'
			AND PAV.HOSP_SVC = 'SLP'
			AND PAV.TOT_AMT_DUE <= 25
			THEN 1
		WHEN PAV.PLM_PT_ACCT_TYPE = 'O'
			AND PAV.HOSP_SVC = 'WIS'
			AND PAV.TOT_AMT_DUE <= 25
			THEN 1
		ELSE 0
		END,
	pav.drg_no,
	actv.actv_cd,
	ACDV.actv_name,
	REVCD.rev_cd,
	sum(actv.chg_tot_amt) AS [TOT_ACTV_CHG_AMT],
	SPROC.PROC_CD_1,
	SPROC.PROC_CD_2,
	SPROC.PROC_CD_3,
	SPROC.PROC_CD_4,
	SPROC.PROC_CD_5,
	SPROC.PROC_CD_6,
	SPROC.PROC_CD_7,
	SPROC.PROC_CD_8,
	SPROC.PROC_CD_9,
	SPROC.PROC_CD_10,
	SPROC.PROC_CD_11,
	SPROC.PROC_CD_12,
	SPROC.PROC_CD_13,
	SPROC.PROC_CD_14,
	SPROC.PROC_CD_15,
	SPROC.PROC_CD_16,
	SPROC.PROC_CD_17,
	SPROC.PROC_CD_18,
	SPROC.PROC_CD_19,
	SPROC.PROC_CD_20,
	SPROC.PROC_CD_21,
	SPROC.PROC_CD_22,
	SPROC.PROC_CD_23,
	SPROC.PROC_CD_24,
	SPROC.PROC_CD_25,
	SPROC.PROC_CD_26,
	SPROC.PROC_CD_27,
	SPROC.PROC_CD_28,
	SPROC.PROC_CD_29,
	SPROC.PROC_CD_30
FROM SMSDSS.BMH_PLM_PtAcct_V AS PAV
INNER JOIN SMSDSS.pyr_dim_v AS PDV ON PAV.Pyr1_Co_Plan_Cd = PDV.pyr_cd
	AND PAV.Regn_Hosp = PDV.orgz_cd
INNER JOIN SMSDSS.hosp_svc_dim_v AS HOS ON PAV.hosp_svc = HOS.hosp_svc
	AND PAV.Regn_Hosp = HOS.orgz_cd
INNER JOIN SMSDSS.pt_type_dim_v AS PTT ON PAV.pt_type = PTT.pt_type
	AND PAV.Regn_Hosp = PTT.orgz_cd
INNER JOIN SMSDSS.FC_DIM_V AS FDV ON PAV.fc = FDV.fc
	AND PAV.Regn_Hosp = FDV.orgz_cd
LEFT OUTER JOIN SMSDSS.DRG_DIM_V AS DDV ON PAV.drg_no = DDV.drg_no
	AND DDV.drg_vers = 'MS-V25'
LEFT OUTER JOIN SMSDSS.PROC_DIM_V AS SPDVA ON PAV.Prin_Icd10_Proc_Cd = SPDVA.proc_cd
LEFT OUTER JOIN SMSDSS.PROC_DIM_V AS SPDVB ON PAV.Prin_Hcpc_Proc_Cd = SPDVB.proc_cd
INNER JOIN SMSMIR.actv AS ACTV ON PAV.PTNO_NUM = ACTV.PT_ID
	AND PAV.unit_seq_no = ACTV.unit_seq_no
	AND PAV.from_file_ind = ACTV.from_file_ind
INNER JOIN SMSDSS.actv_cd_dim_v AS ACDV ON ACTV.actv_cd = ACDV.actv_cd
	AND ACTV.orgz_cd = ACDV.orgz_cd
LEFT OUTER JOIN (
	SELECT PVT.pt_id,
		PVT.unit_seq_no,
		PVT.from_file_ind,
		PVT.[01] AS [PROC_CD_1],
		PVT.[02] AS [PROC_CD_2],
		PVT.[03] AS [PROC_CD_3],
		PVT.[04] AS [PROC_CD_4],
		PVT.[05] AS [PROC_CD_5],
		PVT.[06] AS [PROC_CD_6],
		PVT.[07] AS [PROC_CD_7],
		PVT.[08] AS [PROC_CD_8],
		PVT.[09] AS [PROC_CD_9],
		PVT.[10] AS [PROC_CD_10],
		PVT.[11] AS [PROC_CD_11],
		PVT.[12] AS [PROC_CD_12],
		PVT.[13] AS [PROC_CD_13],
		PVT.[14] AS [PROC_CD_14],
		PVT.[15] AS [PROC_CD_15],
		PVT.[16] AS [PROC_CD_16],
		PVT.[17] AS [PROC_CD_17],
		PVT.[18] AS [PROC_CD_18],
		PVT.[19] AS [PROC_CD_19],
		PVT.[20] AS [PROC_CD_20],
		PVT.[21] AS [PROC_CD_21],
		PVT.[22] AS [PROC_CD_22],
		PVT.[23] AS [PROC_CD_23],
		PVT.[24] AS [PROC_CD_24],
		PVT.[25] AS [PROC_CD_25],
		PVT.[26] AS [PROC_CD_26],
		PVT.[27] AS [PROC_CD_27],
		PVT.[28] AS [PROC_CD_28],
		PVT.[29] AS [PROC_CD_29],
		PVT.[30] AS [PROC_CD_30]
	FROM (
		SELECT pt_id,
			unit_seq_no,
			from_file_ind,
			proc_cd,
			proc_cd_prio
		FROM smsmir.sproc
		WHERE proc_cd_type != 'C'
			AND proc_cd_prio <= 30
		) AS A
	PIVOT(MAX(PROC_CD) FOR PROC_CD_PRIO IN ("01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30")) AS PVT
	) AS SPROC ON PAV.Pt_No = SPROC.pt_id
	AND PAV.unit_seq_no = SPROC.UNIT_SEQ_NO
	AND PAV.from_file_ind = SPROC.from_file_ind
LEFT OUTER JOIN smsmir.mir_actv_proc_seg_xref AS REVCD ON ACTV.actv_cd = REVCD.actv_cd
	AND REVCD.proc_pyr_ind = 'A'
WHERE PAV.PLM_PT_ACCT_TYPE != 'I'
	AND DATEPART(YEAR, PAV.ADM_DATE) = 2018
	AND PAV.tot_chg_amt > 0
	AND LEFT(PAV.PTNO_NUM, 1) != '2'
	AND LEFT(PAV.PTNO_NUM, 4) != '1999'
	AND ACTV.chg_tot_amt != 0
	AND PAV.Pyr1_Co_Plan_Cd IN ('B04', 'B03', 'B05', 'B06', 'K04', 'K11', 'K12', 'X45', 'K10', 'K15')
GROUP BY PAV.Med_Rec_No,
	PAV.PtNo_Num,
	PAV.unit_seq_no,
	PAV.Plm_Pt_Acct_Type,
	PAV.pt_type,
	PTT.pt_type_cd_desc,
	PAV.fc,
	FDV.fc_name,
	CAST(PAV.ADM_DATE AS DATE),
	CAST(PAV.Dsch_Date AS DATE),
	PAV.Pyr1_Co_Plan_Cd,
	PDV.pyr_name,
	PDV.pyr_group2,
	PAV.hosp_svc,
	HOS.hosp_svc_name,
	PAV.tot_chg_amt,
	PAV.tot_adj_amt,
	PAV.tot_pay_amt,
	PAV.Tot_Amt_Due,
	pav.drg_no,
	DDV.drg_name,
	CASE 
		WHEN PAV.Plm_Pt_Acct_Type = 'I'
			THEN PAV.Prin_Icd10_Proc_Cd
		WHEN PAV.Plm_Pt_Acct_Type != 'I'
			THEN PAV.Prin_Hcpc_Proc_Cd
		END,
	COALESCE(SPDVA.alt_clasf_desc, SPDVB.alt_clasf_desc),
	pav.drg_no,
	actv.actv_cd,
	ACDV.actv_name,
	REVCD.rev_cd,
	SPROC.PROC_CD_1,
	SPROC.PROC_CD_2,
	SPROC.PROC_CD_3,
	SPROC.PROC_CD_4,
	SPROC.PROC_CD_5,
	SPROC.PROC_CD_6,
	SPROC.PROC_CD_7,
	SPROC.PROC_CD_8,
	SPROC.PROC_CD_9,
	SPROC.PROC_CD_10,
	SPROC.PROC_CD_11,
	SPROC.PROC_CD_12,
	SPROC.PROC_CD_13,
	SPROC.PROC_CD_14,
	SPROC.PROC_CD_15,
	SPROC.PROC_CD_16,
	SPROC.PROC_CD_17,
	SPROC.PROC_CD_18,
	SPROC.PROC_CD_19,
	SPROC.PROC_CD_20,
	SPROC.PROC_CD_21,
	SPROC.PROC_CD_22,
	SPROC.PROC_CD_23,
	SPROC.PROC_CD_24,
	SPROC.PROC_CD_25,
	SPROC.PROC_CD_26,
	SPROC.PROC_CD_27,
	SPROC.PROC_CD_28,
	SPROC.PROC_CD_29,
	SPROC.PROC_CD_30;
