SELECT DISTINCT [NYS DRG NO] AS DRG
, [MED_REC_NO] AS MRN 

INTO PLATELET_DISTINCT_MRN_PER_DRG_TBL

FROM PLATELET_RAW

WHERE [SERVICE DATE] Between FORMS!RPT_FRM!START_DATE And FORMS!RPT_FRM!END_DATE;

-----

SELECT DISTINCT DRG
, COUNT([MRN]) AS [DISTINCT MRNS PER DRG] 

INTO PLATELET_MRNS_PER_DRG_TBL

FROM PLATELET_DISTINCT_MRN_PER_DRG_TBL

GROUP BY DRG;

-----

SELECT DISTINCT [NYS DRG NO] AS DRG
, SUM([QUANTITY]) AS [SUM OF PLATELETS PER DRG]

INTO PLATELET_SUM_QUANT_PER_DRG_TBL

FROM PLATELET_RAW

WHERE [SERVICE DATE] Between FORMS!RPT_FRM!START_DATE And FORMS!RPT_FRM!END_DATE

GROUP BY [NYS DRG NO];

-----

SELECT DISTINCT PLATELET_DISTINCT_MRN_PER_DRG_TBL.DRG
, PLATELET_MRNS_PER_DRG_TBL.[DISTINCT MRNS PER DRG]
, PLATELET_SUM_QUANT_PER_DRG_TBL.[SUM OF PLATELETS PER DRG]
, PLATELET_SUM_QUANT_PER_DRG_TBL.[SUM OF PLATELETS PER DRG]/PLATELET_MRNS_PER_DRG_TBL.[DISTINCT MRNS PER DRG] AS [AVG PLATELETS PER PERSON] 

INTO AVG_PLATELETS_PER_PERSON_TBL

FROM (
	PLATELET_DISTINCT_MRN_PER_DRG_TBL 
	INNER JOIN PLATELET_MRNS_PER_DRG_TBL 
	ON PLATELET_DISTINCT_MRN_PER_DRG_TBL.DRG=PLATELET_MRNS_PER_DRG_TBL.DRG
	) 
INNER JOIN PLATELET_SUM_QUANT_PER_DRG_TBL 
ON PLATELET_MRNS_PER_DRG_TBL.DRG=PLATELET_SUM_QUANT_PER_DRG_TBL.DRG;

-----

SELECT DISTINCTROW XFUSE_RAW.[MED REC NO]
, XFUSE_RAW.[ENCOUNTER NUM]
, XFUSE_RAW.[PT NAME]
, XFUSE_RAW.[ADMIT DATE TIME]
, XFUSE_RAW.[DISC DATE TIME]
, XFUSE_RAW.[ADMIT HR]
, XFUSE_RAW.[DISC HR]
, XFUSE_RAW.LOS
, XFUSE_RAW.[SERVICE DESC]
, XFUSE_RAW.[DRG NUMBER]
, XFUSE_RAW.[DRG DESC]
, XFUSE_RAW.DOCTOR
, XFUSE_RAW.[PERFORMING DEPT]
, XFUSE_RAW.[PT TYPE]
, XFUSE_RAW.[PT AGE]
, XFUSE_RAW.[ADMIT SOURCE]
, XFUSE_RAW.[PT DISPO]
, Count(*) AS [Count Of XFUSE_RAW] 

INTO XFUSE_QUANT_PER_DAY_TBL

FROM XFUSE_RAW

WHERE [ADMIT DATE TIME] BETWEEN FORMS!RPT_FRM!START_DATE AND FORMS!RPT_FRM!END_DATE

GROUP BY XFUSE_RAW.[MED REC NO]
, XFUSE_RAW.[ENCOUNTER NUM]
, XFUSE_RAW.[PT NAME]
, XFUSE_RAW.[ADMIT DATE TIME]
, XFUSE_RAW.[DISC DATE TIME]
, XFUSE_RAW.[ADMIT HR]
, XFUSE_RAW.[DISC HR]
, XFUSE_RAW.LOS
, XFUSE_RAW.[SERVICE DESC]
, XFUSE_RAW.[DRG NUMBER]
, XFUSE_RAW.[DRG DESC]
, XFUSE_RAW.DOCTOR
, XFUSE_RAW.[PERFORMING DEPT]
, XFUSE_RAW.[PT TYPE]
, XFUSE_RAW.[PT AGE]
, XFUSE_RAW.[ADMIT SOURCE]
, XFUSE_RAW.[PT DISPO];

-----

SELECT MD_TRANSFUSE_ORDERS.DOCTOR
, MD_TRANSFUSE_ORDERS.[ENCOUNTER NUM]
, MD_TRANSFUSE_ORDERS.[SERVICE DESC]
, MD_TRANSFUSE_ORDERS.[DRG DESC]
, Count(MD_TRANSFUSE_ORDERS.[ORDER NUMBER]) AS [ORDER COUNT]
, Sum(MD_TRANSFUSE_ORDERS.UNITS) AS [UNITS ORDERED]

FROM MD_TRANSFUSE_ORDERS

WHERE (
		(
			(MD_TRANSFUSE_ORDERS.[DISC DATE TIME]) Between [FORMS]![RPT_FRM]![START_DATE] 
														And [FORMS]![RPT_FRM]![END_DATE]
		)
	)

GROUP BY MD_TRANSFUSE_ORDERS.DOCTOR
, MD_TRANSFUSE_ORDERS.[ENCOUNTER NUM]
, MD_TRANSFUSE_ORDERS.[SERVICE DESC]
, MD_TRANSFUSE_ORDERS.[DRG DESC];

-----

SELECT HGB_PLATELETS_RAW.Admission_Date
, HGB_PLATELETS_RAW.Disch_Date
, HGB_PLATELETS_RAW.Patient_Name
, HGB_PLATELETS_RAW.Age
, HGB_PLATELETS_RAW.Patient_Account_ID
, HGB_PLATELETS_RAW.Ordering_Physician
, HGB_PLATELETS_RAW.Admitting_Diag
, HGB_PLATELETS_RAW.Order_Entered_Date
, HGB_PLATELETS_RAW.Order_Start_Date
, HGB_PLATELETS_RAW.Order_Stop_Date
, HGB_PLATELETS_RAW.Result_Value_Before
, HGB_PLATELETS_RAW.Result_Date_Before
, HGB_PLATELETS_RAW.Result_Value_After
, HGB_PLATELETS_RAW.Result_Date_After
, Sum(PLATELET_RAW.QUANTITY) AS SumOfQUANTITY

FROM HGB_PLATELETS_RAW 
INNER JOIN PLATELET_RAW 
ON HGB_PLATELETS_RAW.Patient_Account_ID=PLATELET_RAW.[PAV PTNO_NUM]

WHERE (
		(
			(HGB_PLATELETS_RAW.DISCH_DATE) Between [FORMS]![RPT_FRM].[START_DATE] 
												And [FORMS]![RPT_FRM].[END_DATE]
		)
	)

GROUP BY HGB_PLATELETS_RAW.Admission_Date
, HGB_PLATELETS_RAW.Disch_Date
, HGB_PLATELETS_RAW.Patient_Name
, HGB_PLATELETS_RAW.Age
, HGB_PLATELETS_RAW.Patient_Account_ID
, HGB_PLATELETS_RAW.Ordering_Physician
, HGB_PLATELETS_RAW.Admitting_Diag
, HGB_PLATELETS_RAW.Order_Entered_Date
, HGB_PLATELETS_RAW.Order_Start_Date
, HGB_PLATELETS_RAW.Order_Stop_Date
, HGB_PLATELETS_RAW.Result_Value_Before
, HGB_PLATELETS_RAW.Result_Date_Before
, HGB_PLATELETS_RAW.Result_Value_After
, HGB_PLATELETS_RAW.Result_Date_After;

-----

SELECT HGB_RBCS_RAW.Admission_Date
, HGB_RBCS_RAW.Disch_Date
, HGB_RBCS_RAW.Patient_Name
, HGB_RBCS_RAW.Age
, HGB_RBCS_RAW.Patient_Account_ID
, HGB_RBCS_RAW.Ordering_Physician
, HGB_RBCS_RAW.Admitting_Diag
, HGB_RBCS_RAW.Order_Entered_Date
, HGB_RBCS_RAW.Order_Start_Date
, HGB_RBCS_RAW.Order_Stop_Date
, HGB_RBCS_RAW.Result_Value_Before
, HGB_RBCS_RAW.Result_Date_Before
, HGB_RBCS_RAW.Result_Value_After
, HGB_RBCS_RAW.Result_Date_After
, Sum(RBC_RAW.QUANTITY) AS SumOfQUANTITY

FROM HGB_RBCS_RAW 
INNER JOIN RBC_RAW 
ON HGB_RBCS_RAW.Patient_Account_ID=RBC_RAW.[PAV PTNO_NUM]

WHERE (
		(
			(HGB_RBCS_RAW.DISCH_DATE) Between [FORMS]![RPT_FRM].[START_DATE] 
										And [FORMS]![RPT_FRM].[END_DATE]
		)
	)

GROUP BY HGB_RBCS_RAW.Admission_Date
, HGB_RBCS_RAW.Disch_Date
, HGB_RBCS_RAW.Patient_Name
, HGB_RBCS_RAW.Age
, HGB_RBCS_RAW.Patient_Account_ID
, HGB_RBCS_RAW.Ordering_Physician
, HGB_RBCS_RAW.Admitting_Diag
, HGB_RBCS_RAW.Order_Entered_Date
, HGB_RBCS_RAW.Order_Start_Date
, HGB_RBCS_RAW.Order_Stop_Date
, HGB_RBCS_RAW.Result_Value_Before
, HGB_RBCS_RAW.Result_Date_Before
, HGB_RBCS_RAW.Result_Value_After
, HGB_RBCS_RAW.Result_Date_After;
