SELECT DEMOGRAPHIC.GPI
, CLINICAL.FACILITY_ACCOUNT_NO
, POST_RESOURCE.CASE_NO
, POST_RESOURCE.PROCEDURE_ID
, POST_CASE.MAIN_PROCEDURE_ID
, PROCEDURE_tbl.[DESCRIPTION]
, POST_RESOURCE.[START_DATE]
, POST_RESOURCE.RESOURCE_ID
, POST_RESOURCE.ROLE_CODE
, STAFF.NAME

FROM (
	(
		(
			(
				[bmh-orsos].[orsprod].[orsprod].[POST_RESOURCE] as post_resource
				INNER JOIN [bmh-orsos].[orsprod].[ORSPROD].[POST_CASE] as post_case
				ON POST_RESOURCE.CASE_NO = POST_CASE.CASE_NO
			) 
			INNER JOIN [bmh-orsos].[orsprod].[orsprod].[DEMOGRAPHIC] as demographic
			ON POST_CASE.MEDICAL_RECORD_NO = DEMOGRAPHIC.MEDICAL_RECORD_NO
		) 
		INNER JOIN [bmh-orsos].[orsprod].[orsprod].[PROCEDURES] as procedure_tbl
		ON POST_RESOURCE.PROCEDURE_ID = procedure_tbl.PROCEDURE_ID
	) 
	INNER JOIN [bmh-orsos].[orsprod].[orsprod].CLINICAL as clinical
	ON POST_CASE.ACCOUNT_NO = CLINICAL.ACCOUNT_NO
) 
INNER JOIN [bmh-orsos].[orsprod].[orsprod].STAFF as staff
ON POST_RESOURCE.RESOURCE_ID = STAFF.STAFF_ID

WHERE POST_RESOURCE.START_DATE >= '2016-01-01' 
And post_resource.start_date < '2017-01-01'
AND (
	POST_RESOURCE.ROLE_CODE = 2 
	Or 
	POST_RESOURCE.ROLE_CODE = 53 
	Or 
	POST_RESOURCE.ROLE_CODE = 58
) 
AND STAFF.TITLE = 5
;
