SELECT UCase([HCAHPS TOP BOX].[DOCTOR NAME]) AS [DOCTOR NAME]
, UCase([HCAHPS TOP BOX].[LAST NAME LINK]) AS [LAST NAME LINK]
, [HCAHPS TOP BOX].[DISCHARGE QUARTER (YYYYqN)] AS [DISCHARGE QUARTER]
, ROUND(AVG([HCAHPS TOP BOX].[Top Box Rate]),2) AS [TOP BOX PERCENT] 

INTO [HCAHPS TIME SERIES TABLE]

FROM [HCAHPS TOP BOX]
WHERE ((([HCAHPS TOP BOX].[HCAHPS DOMAIN])="COMMUNICATION WITH DOCTORS"))

GROUP BY [HCAHPS TOP BOX].[DOCTOR NAME]
, UCase([HCAHPS TOP BOX].[LAST NAME LINK])
, [HCAHPS TOP BOX].[DISCHARGE QUARTER (YYYYqN)];
