SELECT UCase([HCAHPS HS].[DOCTOR NAME]) AS [DOCTOR NAME]
, UCase([HCAHPS HS].[LAST NAME LINK]) AS [LAST NAME LINK]
, [HCAHPS HS].[QUARTER(YYYYqN)] AS [YEAR / QUARTER]
, 100-[HCAHPS HS].[HSTM DB TOP BOX PERCENTILE RANK] AS [PERCENT OF MDS SCORING BETTER THAN YOU] 

INTO [PHYS RANK REPORT TABLE]

FROM [HCAHPS HS]
WHERE [HCAHPS HS].[QUARTER(YYYYqN)]="2013Q3";
