SELECT A.BILL_NO
, A.VISIT_ID
, A.ADMISSION_DATE
, A.DISCHARGED
, A.PATIENT_TYPE
, A.PHYSICIAN_NO
, A.LAST_NAME
, A.FIRST_NAME
, A.MIDDLE_NAME
, A.ADDRESS1
, A.ADDRESS2
, A.CITY
, A.STATE
, A.ZIP
, A.SEX
, A.MARITAL_STATUS
, A.RACE
, A.V_FINANCIAL_CLS
, B.VISIT_ADMIT_DIAG
, B.ADMIT_DIAG_DESCRIPTION
, B.VISIT_ADMIT_TYPE
, B.VISIT_ADMIT_SOURCE
, B.VISIT_DISCH_SERVICE
, B.VISIT_ADMIT_SERVICE
, B.VISIT_DC_STATUS
, B.VISIT_ADMIT_AGE
, B.S_CPM_HOMECARE_COMMENTS
, C.DATETIME AS [LETTER FAX/PRINT DATE]
, D.*
, E.*

FROM [BMH-3MHIS-DB].[MMM_COR_BMH_LIVE].[dbo].[visit_view]         AS A
JOIN [BMH-3MHIS-DB].[MMM_COR_BMH_LIVE].[dbo].[ctc_visit]          AS B
ON A.VISIT_ID = B._FK_VISIT
JOIN [BMH-3MHIS-DB].[MMM_cor_BMH_LIVE].[DBO].[CTC_DOCUMENTSENT]   AS C
ON B._FK_VISIT = C._FK_VISIT
JOIN [BMH-3MHIS-DB].[MMM_COR_BMH_LIVE].[Dbo].[ctc_letter]         AS D
ON D._FK_DOCUMENTSENT = C._PK
JOIN [BMH-3MHIS-DB].[MMM_COR_BMH_LIVE].[Dbo].[ctc_letterPrintJob] AS E
ON D._PK = E._FK_LETTER

WHERE A.BILL_NO = '14303374'