SELECT TOP 1000 CAST(A.[REFERENCE NUMBER] AS VARCHAR) + CAST(PK AS VARCHAR) AS [Reference Number]
, A.[System]
, A.[MRN]
, A.[Admit Date]
, A.[Discharge Date]
, A.[Payor Code]
, A.[Payor Code Description]
, A.[Payor Sub-Code]
, A.[Payor ID Number]
, ISNULL(A.[Payor City], '') AS [Payor City]
, A.[Payor State]
, A.[Payor TIN]
, A.[Primary Payor]
, A.[Secondary Payor]
, A.[Tertiary Payor]
, A.[Quaternary Payor]
, A.[Primary v Secondary Indicator]
, A.[Risk Sharing Payor]
, A.[Direct/Non Direct Payor]
, A.[Medical Service Code]
, A.[Service Code Description]
, A.[Payment Type]
, A.[Payment Type Description]
, A.[Receivable Type]
, A.[HCRA Line]
, A.[HCRA Line Description]
, A.[Payment Received Date]

FROM smsdss.C_HCRA_STATIC_DATA_2016 AS A

WHERE A.[Payor Code] != '*'
AND A.[Primary v Secondary Indicator] != '0'