-- THIS QUERY GETS PATIENTS WHO HAVE INSERT/REMOVE FOLEY ORDERS THAT
-- ALSO HAVE ORDERS THAT WERE WRITTEN BY A SURGEON
--#####################################################################

-- VARIABLE DECLARATION AND INITIALIZATION
DECLARE @SD DATETIME
DECLARE @ED DATETIME
SET @SD = '2013-06-01';
SET @ED = '2013-06-30';

-- THE WITH STATEMENT IS CREATING A TABLE OUT OF THE QUERY INSIDE THE ()
WITH [SX FLAG] AS (
	SELECT 
	PV.PtNo_Num AS [VISIT ID]
	, PV.Med_Rec_No AS MRN
	, PV.vst_start_dtime AS ADM
	, PV.vst_end_dtime AS DISCH
	, PV.Days_Stay AS LOS
	, PV.pt_type AS [PT TYPE]
	, PV.hosp_svc AS [HOSP SVC]
	, SO.ord_no AS [ORD NUM]
	, X.[ORD DESC]    -- THIS IS FROM THE CROSS APPLY() STATEMENT
	, SO.pty_name AS [PARTY NAME]
	, OSM.ord_sts AS [ORD STS]
	, SOS.prcs_dtime AS [ORD STS TIME]
	, PDV.med_staff_dept AS [MED STAFF DEPT]
	, DATEDIFF(DAY,PV.vst_start_dtime,SOS.prcs_dtime) AS [ADM TO ORD STS IN DAYS]
	-- THE FOLLOWING TWO STATEMENTS ACT AS FLAGS
	, MAX(CASE WHEN [ORD DESC] IN ('INSERT FOLEY', 'REMOVE FOLEY') THEN 1 ELSE 0 END)
		OVER (PARTITION BY PV.PTNO_NUM) AS HasInsertRemoveFoley
	, MAX(CASE WHEN PDV.MED_STAFF_DEPT = 'SURGERY' THEN 1 ELSE 0 END)
		OVER (PARTITION BY PV.PTNO_NUM) AS HasSurgicalOrder

	-- DB(S) IN USE
	FROM smsdss.BMH_PLM_PtAcct_V PV
	JOIN smsmir.sr_ord SO
	ON PV.PtNo_Num = SO.episode_no
	JOIN smsmir.sr_ord_sts_hist SOS
	ON SO.ord_no = SOS.ord_no
	JOIN smsmir.ord_sts_modf_mstr OSM
	ON SOS.hist_sts = OSM.ord_sts_modf_cd
	JOIN smsdss.pract_dim_v PDV
	ON SO.pty_cd = PDV.src_pract_no
    -- THIS IS A CROSS APPLY STATEMENT USED TO SPEED UP THE QUERY INSTEAD
	-- OF USING A CASE IN THE SELECT CLAUSE ABOVE
	CROSS APPLY (
		SELECT
			CASE
				WHEN SO.svc_desc = 'INSERT FOLEY CATHETER' THEN 'INSERT FOLEY'
				WHEN SO.svc_desc = 'INSERT INDWELLING URINARY CATHETER TO GRAVITY DRAINAGE' THEN 'INSERT FOLEY'
				WHEN SO.svc_desc = 'REMOVE INDWELLING URINARY CATHETER' THEN 'REMOVE FOLEY'
				ELSE SO.svc_desc
			END AS [ORD DESC]
			) X

    -- FILTER(S)
	WHERE PV.Adm_Date BETWEEN @SD AND @ED
	-- THE ORDER WE ARE LOOKING FOR, WE WANT PATIENTS WHO HAD AT LEAST
	-- ONE OF THESE ORDERS
	AND SO.svc_cd IN ('PCO_REMFOLEY'
		,'PCO_INSRTFOLEY'
		,'PCO_INSTFOLEY'
		,'PCO_URIMETER'
		)
	AND PV.hosp_svc NOT IN (
		'DIA'
		,'DMS'
		,'EME'
		)
	-- THIS AND() STATEMENT IS GOING TO KICK OUT ORDERS THAT WERE DISCONTINUED
	-- SO IF AN INSERT OR REMOVE FOLEY ORDER WAS DISCONTINUED IT WILL NOT
	-- BE IN THE RESULT SET
	AND SO.ord_no NOT IN (
	    -- SELECT THE ORDER NUMBER THAT WILL BE KICKED OUT
		SELECT SO.ord_no
		
		FROM smsdss.BMH_PLM_PtAcct_V PV
		JOIN smsmir.sr_ord SO
		ON PV.PtNo_Num = SO.episode_no
		JOIN smsmir.sr_ord_sts_hist SOS
		ON SO.ord_no = SOS.ord_no
		JOIN smsmir.ord_sts_modf_mstr OSM
		ON SOS.hist_sts = OSM.ord_sts_modf_cd
		JOIN smsdss.pract_dim_v PDV
	    ON SO.pty_cd = PDV.src_pract_no
		-- KICK OUT ORDERS THAT ARE DISCONTINUED
		WHERE OSM.ord_sts = 'DISCONTINUE'
		-- KICK THESE ORDERS OUT THAT ARE DISCONTINUED
		AND SO.svc_cd IN ('PCO_REMFOLEY'
		,'PCO_INSRTFOLEY'
		,'PCO_INSTFOLEY'
		,'PCO_URIMETER'
		)
	)
	AND PDV.spclty_desc != 'NO DESCRIPTION'
	AND PDV.pract_rpt_name != '?'
	AND PDV.orgz_cd = 'S0X0'
)
SELECT *
FROM [SX FLAG]
-- THIS ENSURES THAT YOU ONLY GET THOSE PATIENTS THAT MEET THE CRITERIA
WHERE HasInsertRemoveFoley = 1
AND HasSurgicalOrder = 1