-- VARIABLE DECLARATION
DECLARE @DAY INT, @MONTH INT, @YEAR INT;

-- VARIABLE INITIALIZATION
SET @DAY = 1;
SET @MONTH = 1;
SET @YEAR = 2019;

-- COLUMN SELECTION
SELECT DISTINCT(nurs_sta) as 'Nursting Station'
, COUNT(NURS_STA) as 'Census'

FROM smsdss.dly_cen_occ_fct

WHERE DATEPART(DAY,CEN_DATE)=@DAY
AND DATEPART(MONTH,CEN_DATE)=@MONTH
AND DATEPART(YEAR,CEN_DATE)=@YEAR
GROUP BY nurs_sta