-- VARIABLE DECLARATION
DECLARE @DAY INT, @MONTH INT, @YEAR INT;

-- VARIABLE INITIALIZATION
SET @DAY = 12;
SET @MONTH = 5;
SET @YEAR = 2013;

-- COLUMN SELECTION
SELECT DISTINCT nurs_sta, COUNT(NURS_STA)AS '# PTS'

FROM smsdss.dly_cen_occ_fct

WHERE DATEPART(DAY,CEN_DATE)=@DAY
AND DATEPART(MONTH,CEN_DATE)=@MONTH
AND DATEPART(YEAR,CEN_DATE)=@YEAR
GROUP BY nurs_sta