SELECT C.FACILITY_ACCOUNT_NO
, P.PATIENT_NAME
, P.PROVIDER_SHORT_NAME
, P.ENTER_PROC_ROOM_DATE

FROM ORSPROD.ORSPROD.CLINICAL C
JOIN ORSPROD.ORSPROD.POST_CASE P
ON C.ACCOUNT_NO = P.ACCOUNT_NO

WHERE C.PATIENT_TYPE = 8
AND P.PROVIDER_SHORT_NAME LIKE '%'
AND C.FACILITY_ACCOUNT_NO < '20000000'
AND C.FACILITY_ACCOUNT_NO NOT LIKE '%J%'

ORDER BY C.FACILITY_ACCOUNT_NO