SELECT *

FROM (
	SELECT EPISODE_NO
	, ORD_NO
	, CAST(ENT_DTIME AS DATE) AS [DATE]
	, CAST(ENT_DTIME AS TIME) AS [TIME]
	, ROW_NUMBER() OVER(
						PARTITION BY EPISODE_NO ORDER BY ORD_NO DESC
						) AS ROWNUM
	FROM smsmir.sr_ord
	WHERE svc_desc = 'DISCHARGE TO'
	AND episode_no < '20000000'
) SRC

WHERE SRC.ROWNUM = 1	