SELECT ORSPROD.DEMOGRAPHIC.GPI
, ORSPROD.CLINICAL.FACILITY_ACCOUNT_NO
, ORSPROD.DEMOGRAPHIC.PATIENT_NAME
, ORSPROD.CLINICAL.ADMIT_DATE
, ORSPROD.CLINICAL.DISCHARGE_DATE
, ORSPROD.POST_RESOURCE.CASE_NO
, ORSPROD.POST_RESOURCE.PROCEDURE_ID
, ORSPROD.PROCEDURES.DESCRIPTION
, ORSPROD.POST_RESOURCE.START_DATE
, ORSPROD.POST_RESOURCE.RESOURCE_ID
, ORSPROD.POST_RESOURCE.ROLE_CODE
, ORSPROD.CODES_ROLE.DESCRIPTION

FROM 
(
	(
		(
			(ORSPROD.POST_RESOURCE 
			INNER JOIN ORSPROD.POST_CASE 
			ON ORSPROD.POST_RESOURCE.CASE_NO = ORSPROD.POST_CASE.CASE_NO
			)
		INNER JOIN ORSPROD.DEMOGRAPHIC 
		ON ORSPROD.POST_CASE.MEDICAL_RECORD_NO = ORSPROD.DEMOGRAPHIC.MEDICAL_RECORD_NO
		)
	INNER JOIN ORSPROD.PROCEDURES 
	ON ORSPROD.POST_RESOURCE.PROCEDURE_ID = ORSPROD.PROCEDURES.PROCEDURE_ID
	)
INNER JOIN ORSPROD.CLINICAL ON ORSPROD.POST_CASE.ACCOUNT_NO = ORSPROD.CLINICAL.ACCOUNT_NO
)
INNER JOIN ORSPROD.CODES_ROLE 
ON ORSPROD.POST_RESOURCE.ROLE_CODE = ORSPROD.CODES_ROLE.CODE

WHERE 
(
	(
		(ORSPROD.POST_RESOURCE.START_DATE) Between '2015-01-01' AND '2015-12-31') 
		AND (
			(ORSPROD.POST_RESOURCE.RESOURCE_ID) = '10470')
)
